TheBigBrainsCompany/TbbcMoneyBundle

- Pair/RatioProvider/YahooFinanceRatioProvider.php
- composer.json
Use curl for requesting the Yahoo finance API for throwing Exceptions if the query went wrong.
> Better error management in YahooFinanceRatioProvider

- Type/MoneyType.php
Fix for schema update issue #31
Doctrine detects is as a varchar type without requiresSQLCommentHint.
Tested, fixes the issue for me.
> Add requiresSQLCommentHint to Money Doctrine type, fix for issue #31

- Form/Type/CurrencyType.php
- Form/Type/MoneyType.php
this updates MoneyType and FormType so they match Symfony 2.7 requirements and don't throw deprecation notices.
> Fix Symfony2.7 deprecation notices for form types

- composer.json
I wanted to use the 3.0 dom crawler but couldn't because of this package, I forked and updated the composer.json to allow for the new 3.0 version. Looking at the code it's only used in the ratio fetcher, and only the filter method is used (which hasn't changed looking at the changelog).
https://github.com/symfony/dom-crawler/blob/master/CHANGELOG.md
Please merge so I can delete fork and use the original.
Thanks!
> [Symfony 3.0] Allow 3.0 dom crawler

- Form/DataTransformer/MoneyToArrayTransformer.php
set the precision of MoneyToLocalizedStringTransformer with $decimals, this fixes a rounding bug (because the symfony transformer uses a precision parameter. 
Current behaviour is when you are on a 3 decimal setting for example and you transform a 100,105 float, you get 100,11.
> Set the precision of MoneyToLocalizedStringTransformer

- Tests/app/config/config_test.yml
Doctrine team added requirement so that either `path` or `dbname` parameter should be set when opening a connection. But for tests we use in-memory sqlite, so neither of those was provided and it threw and exception.
Setting database path as `path: ":memory:"` solves the problem.
> Fixed phpunit tests (were broken because of doctrine dbal changes)

- Pair/RatioProvider/StaticRatioProvider.php
- Tests/Pair/PairManagerTest.php
- Tests/Pair/RatioProvider/StaticRatioProviderTest.php
As described here https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/pull/45#issuecomment-173834262
Tests were not stable because PairManagerTest::testRatioProvider() checks yahoo finance to get exchange rates. It checks it twice in the same test and values can differ between calls.
I have created `StaticRatioProvider` which would basically fetch whatever ratios you provide to it with `StaticRatioProvider::setRatio()`. This is helpful for making tests more stable as results do not change across calls and there's no need to ping yahoo each time since that test tests how `PairManager` works only (yahoo is already tested separately).
> Added static ratio provider (helpful for tests)

- .travis.yml
- composer-template.json
- composer.json
It happens that we did not actually test various versions of symfony, but rather just switched env variables in travis with no effect (doh!). I fixed that so that each version is tested separately.
To make this work every symfony component dependency needed to be changed into according symfony version depending on what we test. 
Unfortunately composer does not support env variables yet (https://github.com/composer/composer/issues/2036), so I've created `composer-template.json` file for that matter which json would use to replace `${env:SYMFONY_VERSION}` variable with actual version on each build.
I have also added phpunit bridge to watch for deprecation messages. I muted it for now with `SYMFONY_DEPRECATIONS_HELPER=weak` because otherwise all builds are failing. It would however still …
> Fixed travis to actually test different versions of symfony correctly, added phpunit bridge

- README.md
Otherwise in symfony3 i got the error described here:
http://stackoverflow.com/questions/35073399/following-manual-instructions-for-bootstrap-3-forms-getting-yml-config-error
> Unrecognized option "form" under "twig"
> form -> resources is obsolete, use instead  form_themes

- DependencyInjection/Compiler/DoctrineTypeCompilerPass.php
- TbbcMoneyBundle.php
- Tests/Fonctionnal/ConfigTest.php
- Tests/app/config/config_test.yml
Thanks for the great bundle!
I was having an issue clearing the cache when the database wasn't present (e.g. on a CI server):
```
$ ./bin/console cache:clear -v
[PDOException (2002)]
SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
Exception trace:
() at /home/vagrant/web/clients.glynnforrest.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
PDO->__construct() at /home/vagrant/web/clients.glynnforrest.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
Doctrine\DBAL\Driver\PDOConnection->__construct() at /home/vagrant/web/clients.glynnforrest.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:45
Doctrine\DBAL\Driver\PDOMySql\Driver->connect() at …
```
> Move doctrine type registration to a compiler pass

- Form/DataTransformer/SimpleMoneyToArrayTransformer.php
- Form/Type/SimpleMoneyType.php
- Resources/config/form_types.xml
- Tests/Form/Type/SimpleMoneyTypeTest.php
Before the modification, the simple money form type used only the default currency.
Yet, in specific case (platform with multiple currencies, for example), it can be useful to be able to choose which currency should be used.
With this PR, it is now possible.
> Add the capability to define a specific currency for the simple money form type

- Resources/config/services.xml
This commit solves 2 deprecation issues:
1. Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "tbbc_money.pair_manager" service to "Tbbc\MoneyBundle\Pair\PairManagerInterface" instead.
2. Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "tbbc_money.formatter.money_formatter" service to "Tbbc\MoneyBundle\Formatter\MoneyFormatter" instead.
> Service alias fix

- Pair/RatioProvider/ECBRatioProvider.php
- README.md
Bugfix for the ECB provider. They redirect from http to https now. Also included it in the README.
> Change url for ECB provider to https as they are redirecting there now.

- Command/RatioFetchCommand.php
- Command/RatioListCommand.php
- Command/RatioSaveCommand.php
- Resources/config/services.xml
The ContainerAwareCommand class has been deprecated, use Symfony\Component\Console\Command\Command with dependency injection instead.
> Removed CommandContainerAware in favor of Command.

- .travis.yml
- composer.json
- Removed PHP 5.4 group, as PHP 5.4 is not tested anyways
- Added `florianv/exchanger`, `php-http/message` and `php-http/guzzle6-adapter` to composer dev requirements, and removed them from travis setup
> Fixing travis memory

- DependencyInjection/Configuration.php
Deprecated constructing a TreeBuilder without passing root node information
Including a BC for older SF versions
> Added root name to treebuilder

- Form/Type/CurrencyType.php
- Form/Type/MoneyType.php
- Form/Type/SimpleMoneyType.php
- README.md
- Tests/Form/Type/CurrencyTypeTest.php
- Tests/Form/Type/MoneyTypeTest.php
- Tests/Form/Type/SimpleMoneyTypeTest.php
I was getting a bit annoyed that by fields label were tbbc_amount and tbbc_currency.
So now its possible to change it
With `MoneyType` you can manipulate the form elements with `amount_options` for the amount field, and `currency_options` for the currency field, fx if you want to change the label.
```php
$form = $this->createFormBuilder()
->add('price', MoneyType::class, [
'data' => Money::EUR(1000), //EUR 10
'amount_options' => array(
'label' => 'Amount',
),
'currency_options' => array(
'label' => 'Currency',
),
])
->getForm();
```
With `CurrencyType` only `currency_options` can be used, and with `SimpleMoneyType` only `amount_options` can be used.
Also added to README and added tests
> Added options so its possible to manipulate the form fields

- Resources/config/services.xml
If we want to access to Money Manager with dependency injection, we need to have this alias.
Else, we have this error:
```
argument "$moneyManager" of method "__construct()" references class "Tbbc\MoneyBundle\Money\MoneyManager" but no such service exists. You should maybe alias this class to the existing "tbbc_money.money_manager" service.
```
> Add alias for MoneyManager Class

- .gitignore
- DependencyInjection/Configuration.php
- Pair/PairManager.php
- Pair/SaveRatioEvent.php
Got this deprecation warning (using Symfony 3.4):
1x: Using Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition::cannotBeEmpty() at path "tbbc_money.currencies" has no effect, consider requiresAtLeastOneElement() instead. In 4.0 both methods will behave the same.
This changes to use `requiresAtLeastOneElement` as the message suggests
> Fix deprecation warning

- README.md
- change-log-6.0-and-versions.md
- src/Resources/config/services.xml
Both classes don't exist in the repository but they were referenced in `services.xml` file.
This makes running the `lint:container` command fail within a Symfony 5/6 project:
```
php bin/console lint:container
In AbstractRecursivePass.php line 176:
Invalid service "tbbc_money.ratio_provider.yahoo_finance": class "Tbbc\MoneyBundle\Pair\RatioProvider\YahooFinanceRatioProvider" does not exist.
lint:container
```
> Remove Yahoo & Google ratio providers

- src/Money/MoneyManager.php
- src/Money/MoneyManagerInterface.php
- src/MoneyException.php
- src/Pair/PairManager.php
- src/PairHistory/PairHistoryManagerInterface.php
- src/TbbcMoneyBundle.php
- src/TbbcMoneyEvents.php
- src/Twig/Extension/CurrencyExtension.php
The suggested Change (performance) from intval to (int) is the most noteable change here.
> chore: small improvements

- .github/workflows/code_checks.yaml
- README.md
- Tests/AppKernel.php
- Tests/Document/DocumentRatioHistoryTest.php
- Tests/Document/DocumentStorageRatioTest.php
- Tests/DocumentDatabaseTrait.php
- Tests/Pair/Storage/DocumentStorageTest.php
- Tests/PairHistory/DocumentPairHistoryManagerTest.php
- Tests/config/config.yaml
- Tests/config/doctrine.yaml
- Tests/config/document.yaml
- composer.json
- src/DependencyInjection/Compiler/PairHistoryCompilerPass.php
- src/DependencyInjection/Compiler/StorageCompilerPass.php
- src/DependencyInjection/Configuration.php
- src/Document/DocumentRatioHistory.php
- src/Document/DocumentStorageRatio.php
- src/Pair/Storage/DocumentStorage.php
- src/PairHistory/DocumentPairHistoryManager.php
- src/Resources/config/document/ratios/DocumentRatioHistory.mongodb.xml
- src/Resources/config/document/ratios/DocumentStorageRatio.mongodb.xml
- src/Resources/config/services.xml
> Add document storage

- Tests/Form/DataTransformer/CurrencyToArrayTransformerTest.php
- Tests/Pair/RatioProvider/ECBRatioProviderTest.php
- Tests/Pair/RatioProvider/ExchangerAdapterRatioProviderTest.php
- src/Command/RatioListCommand.php
- src/Form/DataTransformer/CurrencyToArrayTransformer.php
- src/Form/DataTransformer/MoneyToArrayTransformer.php
- src/Form/DataTransformer/SimpleMoneyToArrayTransformer.php
- src/Money/MoneyManager.php
- src/Pair/PairManager.php
- src/Pair/PairManagerInterface.php
- src/Pair/RatioProvider/ECBRatioProvider.php
- src/Pair/RatioProvider/ExchangerAdapterRatioProvider.php
- src/Pair/Storage/CsvStorage.php
- src/Pair/Storage/DoctrineStorage.php
- src/Pair/Storage/DocumentStorage.php
- src/TbbcMoneyBundle.php
- src/Type/MoneyType.php
> Fix psalm errors

- README.md
- composer.json
i could not run the mongoDB tests local. With this command it works.
Info: It will not work if the port 27017 is already used.
> docs: add infos to run tests local with mongoDB

- change-log-6.0-and-versions.md
- composer.json
https://github.com/TheBigBrainsCompany/TbbcMoneyBundle/issues/171
I need to take a deeper look, if there are tests or bc layers that can be removed.
https://github.com/moneyphp/money/blob/master/CHANGELOG.md#400---2021-05-17
> feat: remove support for "moneyphp/money" < 4.5

- src/DependencyInjection/TbbcMoneyExtension.php
Will fix the deprecation message.
`The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "Tbbc\MoneyBundle\DependencyInjection\TbbcMoneyExtension".`
> feat: fix deprecation for Extension

- composer.json
- src/Resources/config/services.xml
When using pair history ORM is now optional not required.
Removing this should allow MongoDB users to use pair history without having the ORM package installed.
> ORM service is optional

- composer.json
The listSearchIndexes exception that affected mongodb-odm v2.8.0 (and v2.8.1) has been resolved in v2.8.2, so we can relax or remove the constraints now.
> Relax mongodb-odm constraints after listSearchIndexes exception resolution

- src/Resources/views/Form/fields.html.twig
As of Twig 3.12 the spaceless filter has been deprecated.
https://twig.symfony.com/doc/3.x/filters/spaceless.html
> Remove deprecated twig spaceless filter

- src/Formatter/MoneyFormatter.php
https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated
> feat: fix deprecation for PHP 8.4

- src/Pair/Storage/CsvStorage.php
https://www.php.net/manual/en/function.fgetcsv.php
Please see warning for parameter `escape`
Another solution would be to set it to `''`
> fix: deprecation for fgetcsv in CsvStorage.php
